name: Docs
on:
  push:
    ## only works on master branch
    branches:
      - master
jobs:
  merge-to-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge master to gh-pages
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-docs:
    needs: merge-to-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm ci
      - name: Build Docs
        run: npm run docs
      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
