name: Publish
on:
  push:
    ## only works on master branch
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
      - run: npx can-npm-publish
      - name: Install
        run: npm ci
      - name: Publish
        ## prepublishOnly has done build and test tasks
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Git-tag
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
  merge-to-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge master to gh-pages
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-docs:
    needs: merge-to-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm ci
      - name: Build Docs
        run: npm run docs
      - name: Publish Docs
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.0
        with:
          dir: docs
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
